name: Build deploy PROD

on:
  workflow_dispatch:
    inputs:
      manual_deploy:
        description: "Manual Deploy"
        required: true
        type: boolean
        default: true
  push:
    branches:
      - main

env:
  MEMORY: 128MB
  TIMEOUT: 60
  REGION: us-east1

jobs:
  deploy:
    name: Deploy Function and Scheduler
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Deploy Cloud Function from Source Code in functions folder
        run: |
          gcloud functions deploy trigger-update-location \
            --runtime python310 \
            --trigger-http \
            --allow-unauthenticated \
            --memory $MEMORY \
            --timeout $TIMEOUT \
            --region $REGION \
            --source ./functions

      - name: Create Cloud Scheduler Job
        run: |
          gcloud scheduler jobs create http my-scheduler-job \
            --schedule "*/5 * * * *" \
            --uri "https://$REGION-${{ secrets.GCP_PROJECT }}.cloudfunctions.net/trigger-update-location" \
            --http-method GET \
            --time-zone "America/Sao_Paulo" \
          || echo "Scheduler already exists, updating it..."

      - name: Update Cloud Scheduler Job
        run: |
          gcloud scheduler jobs update http my-scheduler-job \
            --schedule "*/5 * * * *" \
            --uri "https://$REGION-${{ secrets.GCP_PROJECT }}.cloudfunctions.net/trigger-update-location" \
            --http-method GET \
            --time-zone "America/Sao_Paulo"
